branches:
  only:
    - master
    - develop

init:
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true")
      {
          Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_TAG_NAME.TrimStart("v"))"
          $env:APPVEYOR_CACHE_SKIP_RESTORE = "true"
      }
      else
      {
          Update-AppveyorBuild -Version "dev-$($env:APPVEYOR_REPO_COMMIT.Substring(0, 7))"
      }

image:
  - Visual Studio 2019

platform: Any CPU
  
configuration: Release

before_build:
  - nuget restore

build:
  project: DBDesign.PosiStageDotNet.sln

artifacts:
  - name: Build
    path: src\DBDesign.PosiStageDotNet\bin\$(configuration)